Metrics/BlockLength:
  CountComments: false
  Max: 300
  ExcludedMethods: []
  Exclude:
    - "spec/**/*"

Metrics/LineLength:
  Description: 'Limit lines to 150 characters.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#80-character-limits'
  Max: 150

Metrics/MethodLength:
  Description: 'Limit lines to 150 characters.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#80-character-limits'
  Max: 150

Metrics/PerceivedComplexity:
  Description: >-
                 A complexity metric that is strongly correlated to the number
                 of test cases needed to validate a method.
  Enabled: false

Metrics/CyclomaticComplexity:
  Description: >-
                 A complexity metric that is strongly correlated to the number
                 of test cases needed to validate a method.
  Enabled: false

Style/MultipleComparison:
  Description: 'Better not use n==1 || n==0'
  Enabled: false

Metrics/ParameterLists:
  Max: 7
  CountKeywordArgs: true
